In [1]:
import numpy as np

In [14]:
X = np.array(([0,0,0],[0,0,1],[0,1,0], \
              [0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]), dtype=float)

In [15]:
y = np.array(([1], [0], [0], [0], [0], \
              [0], [0], [1]), dtype=float)

In [16]:
xPredicted = np.array(([0,0,1]), dtype=float)
X = X/np.amax(X, axis=0) 
xPredicted = xPredicted/np.amax(xPredicted, axis=0)

In [20]:
lossFile = open("SumSquaredLossList.csv","w")

In [18]:
class Neural_Network (object):
    def __init__(self):
        self.inputLayerSize = 3 
        self.outputLayerSize = 1 
        self.hiddenLayerSize = 4 
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
    def feedForward(self, X):
        self.z = np.dot(X, self.W1)
        self.z2 = self.activationSigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2)
        o = self.activationSigmoid(self.z3)
        return o
    def backwardPropagate(self, X, y, o):
        self.o_error = y - o
        self.o_delta = self.o_error*self.activationSigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error*self.activationSigmoidPrime(self.z2)
        self.W1 += X.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.o_delta)
    def trainNetwork(self, X, y):
        o = self.feedForward(X)
        self.backwardPropagate(X, y, o)
    def activationSigmoid(self, s):
        return 1/(1+np.exp(-s))
    def activationSigmoidPrime(self, s):
        return s * (1 - s)
    def saveSumSquaredLossList(self,i,error):
        lossFile.write(str(i)+","+str(error.tolist())+'\n')
    def saveWeights(self):
        np.savetxt("weightsLayer1.txt", self.W1, fmt="%s")
        np.savetxt("weightsLayer2.txt", self.W2, fmt="%s")
    def predictOutput(self):
        print ("Predicted XOR output data based on trained weights: ")
        print ("Expected (X1-X3): \n" + str(xPredicted))
        print ("Output (Y1): \n" + str(self.feedForward(xPredicted)))

myNeuralNetwork = Neural_Network()
trainingEpochs = 1000

In [21]:
for i in range(trainingEpochs):
    print("Epoch # "+str(i)+"\n")
    print("Network Input : \n" + str(X))
    print("Expected Output of XOR Gate Neural Network: \n" + str(y))
    print("Actual Output from XOR Gate Neural Network: \n" + str(myNeuralNetwork.feedForward(X)))
    Loss = np.mean(np.square(y - myNeuralNetwork.feedForward(X)))
    myNeuralNetwork.saveSumSquaredLossList(i,Loss)
    print ("Sum Squared Loss: \n" + str(Loss))
    print ("\n")
    myNeuralNetwork.trainNetwork(X, y)
myNeuralNetwork.saveWeights()
myNeuralNetwork.predictOutput()

Epoch # 0

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.72776284]
 [0.75433521]
 [0.57602911]
 [0.6122943 ]
 [0.79878881]
 [0.81140355]
 [0.67539575]
 [0.71332487]]
Sum Squared Loss: 
0.39807873307827446


Epoch # 1

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.536949  ]
 [0.54631388]
 [0.34468649]
 [0.36934539]
 [0.55327312]
 [0.55954386]
 [0.37909808]
 [0.41113266]]
Sum Squared Loss: 
0.2347225559044358


Epoch # 2

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Netwo

 [0.3486783 ]]
Sum Squared Loss: 
0.11320080995056175


Epoch # 155

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.58171848]
 [0.20809   ]
 [0.18955479]
 [0.23072674]
 [0.22250058]
 [0.24530366]
 [0.24976503]
 [0.35058912]]
Sum Squared Loss: 
0.11265302243504065


Epoch # 156

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.58332446]
 [0.20763103]
 [0.18934648]
 [0.23145827]
 [0.22142046]
 [0.24495662]
 [0.24980756]
 [0.35250271]]
Sum Squared Loss: 
0.1121051867096677


Epoch # 157

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1

 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.79222382]
 [0.14481841]
 [0.11548802]
 [0.11878589]
 [0.13481125]
 [0.10460134]
 [0.13926441]
 [0.74220534]]
Sum Squared Loss: 
0.02581988154764161


Epoch # 345

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.79270305]
 [0.14446182]
 [0.11523773]
 [0.11821533]
 [0.13455361]
 [0.10404677]
 [0.13868641]
 [0.74334381]]
Sum Squared Loss: 
0.02564157009180777


Epoch # 346

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.79317847]
 [0.14410589]
 [0.11498863]
 [0.11765042]
 [0.13429673]
 [0.10349761]
 [0.13811331]
 [0.744471

 [0.85465565]]
Sum Squared Loss: 
0.010496674216053745


Epoch # 535

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.84783381]
 [0.0953578 ]
 [0.08234636]
 [0.06575894]
 [0.09832168]
 [0.05374413]
 [0.08214906]
 [0.85495801]]
Sum Squared Loss: 
0.010461756711666576


Epoch # 536

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.84802349]
 [0.09518429]
 [0.08222493]
 [0.06563196]
 [0.09818546]
 [0.05362792]
 [0.08200402]
 [0.85525882]]
Sum Squared Loss: 
0.01042705099818726


Epoch # 537

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]


 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.87522642]
 [0.07148704]
 [0.06465598]
 [0.05058997]
 [0.07873975]
 [0.04044146]
 [0.06444845]
 [0.89298744]]
Sum Squared Loss: 
0.006357416732447007


Epoch # 721

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.87534233]
 [0.0713919 ]
 [0.06458064]
 [0.05053721]
 [0.07865764]
 [0.04039798]
 [0.06438538]
 [0.89312786]]
Sum Squared Loss: 
0.006343394761738723


Epoch # 722

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.87545798]
 [0.07129703]
 [0.06450547]
 [0.05048464]
 [0.07857573]
 [0.04035468]
 [0.06432254]
 [0.8932

0.0044795583324314945


Epoch # 905

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.8928955 ]
 [0.05762373]
 [0.05314778]
 [0.04328021]
 [0.06630329]
 [0.03469143]
 [0.05561882]
 [0.9128521 ]]
Sum Squared Loss: 
0.004472195278642276


Epoch # 906

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expected Output of XOR Gate Neural Network: 
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Actual Output from XOR Gate Neural Network: 
[[0.89297393]
 [0.0575651 ]
 [0.05309666]
 [0.04325034]
 [0.06624842]
 [0.03466915]
 [0.05558246]
 [0.91293418]]
Sum Squared Loss: 
0.004464854743473967


Epoch # 907

Network Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]]
Expecte